### ISSUE TITLE
Missing "schema" in connection_keys

### ISSUE THREAD

**Issue by andymalo43** [kaysef/dbt-db2fori#1]
Hi,

First of all, a big thank you for your work ! I tried it and I was in front of a little issue :

In the file connections.py (dbt/adapters/db2_for_i), the "schema" string is not present. With dbt run it results, a missing argument for create table / view / etc..

after adding it, everything is runing fine : 

![image](https://user-images.githubusercontent.com/87163807/212521113-a1d7c0bd-aa8d-4656-a03d-64cd90bf29d2.png)

Have a good day and thank you for this amazing adapter for IBMi <3

**Comment by kaysef** [comment]
Hey Andy,

Thanks for reaching out and I'm glad you find the adapter useful. I have
published an update to Pypi. Could you please try it and let me know if it
works for your case?

Thanks,
Qwamz

**Comment by andymalo43** [comment]
Hi @kaysef ,
sorry for a not responding, I didn't have the time to test your extension.

I got an error after initialize a new venv and installing dbt-db2fori :

first my versions : I tried with dbt-core 1.4.1 but there was always the 'Not compatible'

![image](https://user-images.githubusercontent.com/87163807/215360854-3bb7ea6b-fa3d-4edc-87a4-4cc5ee48b812.png)

when I launch dbt here is the log error 
![image](https://user-images.githubusercontent.com/87163807/215360947-d9267429-81cb-49e8-ac26-ca1789e088ee.png)

**Comment by andymalo43** [comment]
SOrry, I close the issue by mistake

**Comment by kaysef** [comment]
Hey @andymalo43, the adapter doesn't support `dbt-core` v1.4 yet. You'd have to use v1.3

**Comment by andymalo43** [comment]
Hi ! 
Thanks @kaysef for your response. I got the same behavior with 1.2.0 to 1.3 :/ 
I will send you some screenshots tomorrow morning, thanks you again for you availability

**Comment by kaysef** [comment]
@andymalo43 the adapter is now compatible with `dbt-core v1.4`. All the errors you were seeing have been fixed

**Comment by andymalo43** [comment]
WOW @kaysef  You rock ! It works great ! 
My table model is well implemented, I'm gonna test the others methods (incremental , view, ephemeral) :) 

Thank you again for this amazing work ! IBMi still have a long way to live :)

**Comment by andymalo43** [comment]
Hi @kaysef !

I tried with the new version (1.3,1.4) and it's fine. I have a problem with the increemental model, it says there is no merge or insert 
I will send the screen after :) 

Do you think that your connector can Be official for dbt ? I am not a python expert but I can help and maybe it can Be support by other people ? 

Have a great day

**Comment by kaysef** [comment]
Hi @andymalo43, thanks for testing the adapter. Definitely will be a pleasure to have others help with improving this adapter. For the incremental model piece, can you please close this and open that in another issue?

**Comment by andymalo43** [comment]
Thank you @kaysef !
 
Sorry for the late answering. 

I'm going to watch if there are some interested people in the IBMi community :) 

Have a great day
